export const NAME_REQUIERED='El nombre es requerido';
export const NAME_MIN_LENGHT='El nombre debe tener al menos 5 caracteres';
export const NAME_MAX_LENGTH='El nombre no puede tener más de 20 caracteres';
export const NAME_NO_SPECIAL_CHARACTERS='No puede contener caracteres especiales';
export const NAME_MAX_3_NUMBERS='No puede contener más de 3 números';
export const NAME_CANNOT_ONLY_NUMBERS='No puede contener solo números';
export const NAME_LENGHT='El nombre debe tener entre 5 y 20 caracteres';
export const GAME_NOT_FOUND='Game not found';
export const SERVICE_ERROR="Error in the service";
